//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaControle.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemaControle.Domain.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição da categoria é obrigatória..
        /// </summary>
        public static string CGR0001 {
            get {
                return ResourceManager.GetString("CGR0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalidade da categoria inválida. Valores permitidos: Despesa (1), Receita (2) ou Ambas (3)..
        /// </summary>
        public static string CGR0002 {
            get {
                return ResourceManager.GetString("CGR0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O GUID informado não está associado a nenhuma pessoa cadastrada..
        /// </summary>
        public static string CGR0003 {
            get {
                return ResourceManager.GetString("CGR0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição da  transferencia é obrigatória..
        /// </summary>
        public static string CGR0004 {
            get {
                return ResourceManager.GetString("CGR0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TipoTransacao da transacoes inválida. Valores permitidos: Despesa (1), Receita (2)..
        /// </summary>
        public static string CGR0005 {
            get {
                return ResourceManager.GetString("CGR0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor informado deve ser maior que zero..
        /// </summary>
        public static string CGR0006 {
            get {
                return ResourceManager.GetString("CGR0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O GUID informado não está associado a nenhuma categoria cadastrada..
        /// </summary>
        public static string CGR0007 {
            get {
                return ResourceManager.GetString("CGR0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O GUID informado não está associado a nenhuma pessoa cadastrada..
        /// </summary>
        public static string CGR0008 {
            get {
                return ResourceManager.GetString("CGR0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa menor de idade só pode cadastrar despesa..
        /// </summary>
        public static string CGR0009 {
            get {
                return ResourceManager.GetString("CGR0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A categoria selecionada não pode ser utilizada para o tipo de transação informado. Verifique a finalidade da categoria..
        /// </summary>
        public static string CGR0010 {
            get {
                return ResourceManager.GetString("CGR0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da pessoa é obrigatório e não pode estar vazio..
        /// </summary>
        public static string CGR0011 {
            get {
                return ResourceManager.GetString("CGR0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A idade informada é inválida. Informe um valor entre 0 e 120 anos..
        /// </summary>
        public static string CGR0012 {
            get {
                return ResourceManager.GetString("CGR0012", resourceCulture);
            }
        }
    }
}
